# Generated by Django 5.0.6 on 2024-09-22 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter a title for the video.', max_length=50, null=True)),
                ('views', models.PositiveIntegerField(default=0, help_text='View count of the video.')),
                ('uploadDate', models.DateTimeField(editable=False, help_text='Upload date for the video.')),
            ],
        ),
        migrations.CreateModel(
            name='VideoInstance',
            fields=[
                ('id', models.CharField(default='IpwfN5', editable=False, help_text='6-character alphanumeric id for video.', max_length=6, primary_key=True, serialize=False)),
                ('expires', models.DateTimeField(editable=False, help_text='Expiry time of the video.')),
                ('file', models.FileField(upload_to='uploads/')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clip_sharing_app.video')),
            ],
        ),
    ]
