# Generated by Django 5.0.6 on 2024-09-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip_sharing_app', '0003_rename_uploaddate_video_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinstance',
            name='id',
            field=models.CharField(default='Wg5xgr', help_text='6-character alphanumeric id for video.', max_length=6, primary_key=True, serialize=False),
        ),
    ]
