# Generated by Django 5.0.6 on 2024-10-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip_sharing_app', '0015_alter_video_expires_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='expires',
            field=models.DateTimeField(help_text='Expiry time of the video.', null=True),
        ),
    ]
