# Generated by Django 5.0.6 on 2024-10-12 20:29

import clip_sharing_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip_sharing_app', '0016_alter_video_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinstance',
            name='file',
            field=models.FileField(upload_to=clip_sharing_app.models.upload_to),
        ),
    ]
