# Generated by Django 5.0.6 on 2024-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clip_sharing_app', '0017_alter_videoinstance_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='views',
        ),
        migrations.AddField(
            model_name='video',
            name='shares',
            field=models.PositiveIntegerField(default=0, help_text='Share count of the video.'),
        ),
    ]
