# Generated by Django 5.0.6 on 2024-10-22 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clip_sharing_app', '0018_remove_video_views_video_shares'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='shares',
            new_name='views',
        ),
    ]
